services:
  registry:
    image: registry:3
    container_name: tamochi-registry
    restart: always
    network_mode: bridge
    ports:
      - "${HOST_PORT_REG}:5000"
    volumes:
      - ${HOST_VOLUME_DATA}:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "[${CORS_ALLOW_ORIGIN}]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: "[HEAD,GET,OPTIONS,DELETE]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: "[Authorization,Accept,Cache-Control]"
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: "[Docker-Content-Digest]"

  registry-ui:
    image: joxit/docker-registry-ui:2
    container_name: tamochi-registry-ui
    restart: always
    network_mode: bridge
    ports:
      - "${HOST_PORT_UI}:80"
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_URL=${REGISTRY_URL}
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=tamochi's hub