services:
  registry:
    image: registry:3
    container_name: tamochi-registry
    restart: always
    ports:
      - "${HOST_PORT_REG}:5000"
    volumes:
      - ${HOST_VOLUME_DATA}:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"