services:
  postgresql:
    image: postgres:18-alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      TZ: Asia/Shanghai
    volumes:
      - ${HOST_VOLUME_SQL}:/var/lib/postgresql/data
    shm_size: 2g
    ports:
      - "${HOST_PORT_SQL}:5432"
    network_mode: bridge

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

      TZ: Asia/Shanghai
    volumes:
      - ${HOST_VOLUME_WEB}:/var/lib/pgadmin
    ports:
      - "${HOST_PORT_WEB}:80"
    depends_on:
      - postgresql
    network_mode: bridge