services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:latest
    container_name: cyberchef
    restart: unless-stopped
    network_mode: bridge
    ports:
      - ${HOST_PORT}:80
    mem_limit: 256m