services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    network_mode: bridge
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ${HOST_VOLUME}:/var/lib/onlyoffice
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - TZ=Asia/Shanghai